import React from 'react'
import Header from "../MyComponents/Header";
import Footer from "../MyComponents/Footer";
// import './style.css';

function Cookies() {
    React.useEffect(() => {
        var tag = document.getElementById("cookies");
    
        tag.innerHTML = ` <section class="cookies-section">
        <h1 class="cookies-heading-one">Cookie Policy</h1>
        <span class="cookies-span">Updated at 2021-06-25</span>
        <h2 class="cookies-heading-two">Definitions and key terms</h2>
        <h4 class="cookies-heading-four">To help explain things as clearly as possible in this Cookie Policy, every time
            any of these terms are
            referenced, are strictly
            defined as:</h4>
        <ul class="cookies-unorder-list">
            <li class="cookies-li-list">Cookie: small amount of data generated by a website and saved by your web
                browser.
                It is used to identify your browser,
                provide analytics, remember information about you such as your language preference or login information.
            </li>
            <li class="cookies-li-list">Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to
                www.starmapping.in, that is responsible for
                your information under this Cookie Policy.</li>
            <li class="cookies-li-list">Device: any internet connected device such as a phone, tablet, computer or any
                other
                device that can be used to visit
                www.starmapping.in and use the services.</li>
            <li class="cookies-li-list">Personal Data: any information that directly, indirectly, or in connection with
                other information — including a personal
                identification number — allows for the identification or identifiability of a natural person.</li>
            <li class="cookies-li-list">Service: refers to the service provided by www.starmapping.in as described in
                the
                relative terms (if available) and on this
                platform.</li>
            <li class="cookies-li-list">Third-party service: refers to advertisers, contest sponsors, promotional and
                marketing partners, and others who provide
                our content or whose products or services we think may interest you.</li>
            <li class="cookies-li-list">Website: www.starmapping.in."’s" site, which can be accessed via this URL:
                www.starmapping.in</li>
            <li class="cookies-li-list">You: a person or entity that is registered with www.starmapping.in to use the
                Services.</li>
        </ul>




        <h2 class="cookies-heading-two">Introduction</h2>
        <p class="cookies-content">This Cookie Policy explains how www.starmapping.in and its affiliates (collectively
            "www.starmapping.in", "we", "us", and
            "ours"), use cookies and similar technologies to recognize you when you visit our website, including without
            limitation
            www.starmapping.in and any related URLs, mobile or localized versions and related domains / sub-domains
            ("Websites"). It
            explains what these technologies are and why we use them, as well as the choices for how to control them.
        </p>



        <h2 class="cookies-heading-two">What is a cookie?</h2>
        <p class="cookies-content">A cookie is a small text file that is stored on your computer or other internet
            connected
            device in order to identify your browser,
            provide analytics, remember information about you such as your language preference or login information.
            They're
            completely
            safe and can't be used to run programs or deliver viruses to your device.</p>

        <h2 class="cookies-heading-two">Why do we use cookies?</h2>
        <h4 class="cookies-heading-four">We use first party and/or third party cookies on our website for various
            purposes such as:</h4>
        <ul class="cookies-unorder-list">
            <li class="cookies-li-list">To facilitate the operation and functionality of our website;</li>
            <li class="cookies-li-list">To improve your experience of our website and make navigating around them
                quicker and easier;</li>
            <li class="cookies-li-list">To allow us to make a bespoke user experience for you and for us to understand
                what is useful or of interest to
                you;</li>
            <li class="cookies-li-list">To analyze how our website is used and how best we can customize it;</li>
            <li class="cookies-li-list">To identify future prospects and personalize marketing and sales interactions
                with it;</li>
            <li class="cookies-li-list">To facilitate the tailoring of online advertising to your interests.</li>
        </ul>




        <h2 class="cookies-heading-two">What type of cookies does www.starmapping.in use?</h2>
        <p class="cookies-content">Cookies can either be session cookies or persistent cookies. A session cookie expires
            automatically when you
            close your
            browser. A persistent cookie will remain until it expires or you delete your cookies. Expiration dates are
            set
            in the cookies
            themselves; some may expire after a few minutes while others may expire after multiple years. Cookies placed
            by
            the website
            you’re visiting are called “first party cookies”.
            Strictly Necessary cookies are necessary for our website to function and cannot be switched off in our
            systems.
            They are
            essential in order to enable you to navigate around the website and use its features. If you remove or
            disable
            these cookies, we
            cannot guarantee that you will be able to use our website.</p>





        <h2 class="cookies-heading-two">We use the following types of cookies in our website:</h2>

        <h2 class="cookies-heading-two">Essential Cookies</h2>
        <p class="cookies-content">We use essential cookies to make our website work. These cookies are strictly
            necessary to enable core
            functionality such as
            security, network management, your cookie preferences and accessibility. Without them you wouldn't be able
            to
            use basic
            services. You may disable these by changing your browser settings, but this may affect how the Websites
            function.</p>





        <h2 class="cookies-heading-two">Performance and Functionality Cookies</h2>
        <p class="cookies-content">These cookies are used to enhance the performance and functionality of our website
            but are non-essential to their
            use.
            However, without these cookies, certain functionality like videos may become unavailable or you would be
            required to enter your
            login details every time you visit the website as we would not be able to remember that you had logged in
            previously.</p>




        <h2 class="cookies-heading-two">Marketing Cookies</h2>
        <p class="cookies-content">These account-based marketing cookies enable us to identify future prospects and
            personalize sales and marketing
            interactions
            with them.</p>



        <h2 class="cookies-heading-two">Analytics and Customization Cookies</h2>
        <p class="cookies-content">These cookies collect information that is used to help us understand how our website
            is being used or how
            effective our
            marketing campaigns are, or to help us customize our website for you.
            We use cookies served by Google Analytics to collect limited data directly from end-user browsers to enable
            us
            to better
            understand your use of our website. Further information on how Google collects and uses this data can be
            found
            at:
            https://www.google.com/policies/privacy/partners/. You can opt-out of all Google supported analytics on our
            Websites by
            visiting: https://tools.google.com/dlpage/gaoptout.</p>




        <h2 class="cookies-heading-two">Social Media Cookies</h2>
        <p class="cookies-content">These cookies are used when you share information using a social media sharing button
            or “like” button on our
            Site or you link
            your account or engage with our content on or through a social networking website such as Facebook, Twitter
            or
            Google+. The
            social network will record that you have done this. These cookies may also include certain code that has
            been
            placed on the
            platform to help track conversions from ads, optimize ads based on collected data, build targeted audiences
            for
            future ads, and remarket to qualified users who have already taken certain action on the platform.</p>



        <h2 class="cookies-heading-two">How you can manage cookies?</h2>
        <p class="cookies-content">Most browsers allow you to control cookies through their 'settings' preferences.
            However, if you limit the
            ability of websites to set
            cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may
            also stop you from
            saving customized settings like login information. Browser manufacturers provide help pages relating to
            cookie
            management in
            their products.</p>
        <h4 class="cookies-heading-four">Browser manufacturers provide help pages relating to cookie management in their
            products. Please see below for
            more
            information.</h4>

        <ul class="cookies-unorder-list">
            <li class="cookies-li-list">Google Chrome</li>
            <li class="cookies-li-list">Internet Explorer</li>
            <li class="cookies-li-list">Mozilla Firefox</li>
            <li class="cookies-li-list">Safari (Desktop)</li>
            <li class="cookies-li-list">Safari (Mobile)</li>
            <li class="cookies-li-list">Android Browser</li>
            <li class="cookies-li-list">Opera</li>
            <li class="cookies-li-list">Opera Mobile</li>
        </ul>






        <h2 class="cookies-heading-two">Blocking and disabling cookies and similar technologies</h2>
        <p class="cookies-content">Wherever you're located you may also set your browser to block cookies and similar
            technologies, but this action may block our
            essential cookies and prevent our website from functioning properly, and you may not be able to fully
            utilize all of its features
            and services. You should also be aware that you may also lose some saved information (e.g. saved login
            details, site
            preferences) if you block cookies on your browser. Different browsers make different controls available to
            you. Disabling a
            cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself
            from within your
            browser, you should visit your browser's help menu for more information.</p>





        <h2 class="cookies-heading-two">Changes To Our Cookie Policy</h2>
        <p class="cookies-content">We may change our Service and policies, and we may need to make changes to this
            Cookie Policy so that they accurately
            reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through
            our Service) before
            we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect.
            Then, if you
            continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to
            this or any updated
            Cookie Policy, you can delete your account.</p>




        <h2 class="cookies-heading-two">Your Consent</h2>
        <p class="cookies-content">By using our website, registering an account, or making a purchase, you hereby
            consent to our Cookie Policy and agree to its
            terms.</p>

        <h2 class="cookies-heading-two">Contact Us</h2>
        <p class="cookies-content">Don't hesitate to contact us if you have any questions regarding our Cookie Policy.
        </p>
        <ul class="cookies-unorder-list">
            <li class="cookies-li-list">Via Email: help@starmapping.in</li>
        </ul>
    </section>
 `;

        return () => {};
      }, []);
    
    return (
        <>
        <Header/>
        <div className="container" style={{color:"white"}} id="cookies">
            
        </div>
        <Footer/>
        </>
    )
}

export default Cookies
