import React from "react";
import Header from "../MyComponents/Header";
import Footer from "../MyComponents/Footer";

function Return() {
  React.useEffect(() => {
    var tag = document.getElementById("return");

    tag.innerHTML = `    <section class="cookies-section">
    <h1 class="cookies-heading-one">Return & Refund Policy</h1>
    <span class="cookies-span">Updated at 2021-06-25</span>



    <h2 class="cookies-heading-two">Definitions and key terms</h2>
    <h4 class="cookies-heading-four">To help explain things as clearly as possible in this Return & Refund Policy, every time any of these terms
        are referenced, are
        strictly defined as:</h4>

    <ul class="cookies-unorder-list">
        <li class="cookies-li-list">Cookie: small amount of data generated by a website and saved by your web browser. It is used to
            identify your browser,
            provide analytics, remember information about you such as your language preference or login information.
        </li>
        <li class="cookies-li-list">Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to www.starmapping.in,
            that is responsible for
            your information under this Return & Refund Policy.</li>
        <li class="cookies-li-list">Customer: refers to the company, organization or person that signs up to use the www.starmapping.in
            Service to manage
            the relationships with your consumers or service users.</li>
        <li class="cookies-li-list">Device: any internet connected device such as a phone, tablet, computer or any other device that can be
            used to visit
            www.starmapping.in and use the services.</li>
        <li class="cookies-li-list">Service: refers to the service provided by www.starmapping.in as described in the relative terms (if
            available) and on this
            platform.</li>
        <li class="cookies-li-list">Website: www.starmapping.in."’s" site, which can be accessed via this URL: www.starmapping.in</li>
        <li class="cookies-li-list">You: a person or entity that is registered with www.starmapping.in to use the Services.</li>
    </ul>




    <h2 class="cookies-heading-two">Return & Refund Policy</h2>

    <p class="cookies-content">Thanks for shopping at www.starmapping.in. We appreciate the fact that you like to buy the stuff we build. We
        also want to
        make sure you have a rewarding experience while you’re exploring, evaluating, and purchasing our products.
    </p>


    <p class="cookies-content">As with any shopping experience, there are terms and conditions that apply to transactions at
        www.starmapping.in. We’ll be as
        brief as our attorneys will allow. The main thing to remember is that by placing an order or making a
        purchase at
        www.starmapping.in, you agree to the terms set forth below along with Policy.</p>

    <p class="cookies-content">If there’s something wrong with the you bought, or if you are not happy with it, you will not be able to
        issue a refund for your
        item.</p>


    <h2 class="cookies-heading-two">Refunds</h2>
    <p class="cookies-content">We at ourselves to serving our customers with the best products. Every single product that you choose is
        thoroughly inspected,
        checked for defects and packaged with utmost care. We do this to ensure that you fall in love with our
        products.
        Sadly, there are times when we may not have the product(s) that you choose in stock, or may face some issues
        with our
        inventory and quality check. In such cases, we may have to cancel your order. You will be intimated about it
        in advance so that
        you don't have to worry unnecessarily about your order. If you have purchased via Online payment (not Cash
        on Delivery), then
        you will be refunded once our team confirms your request.
        We carry out thorough quality check before processing the ordered item. We take utmost care while packing
        the product. At the
        same time we ensure that the packing is good such that the items won’t get damaged during transit. Please
        note that
        www.starmapping.in is not liable for damages that are caused to the items during transit or transportation.
    </p>


    <h4 class="cookies-heading-four">We follow certain policies to ensure transparency, efficiency and quality customer care:</h4>

    <ul class="cookies-unorder-list">
        <li class="cookies-li-list">We DO NOT allow returns on sold products - online or in retail outlets.</li>
        <li class="cookies-li-list">We DO NOT accept returned goods, as we believe that customers should get the best quality products.</li>
        <li class="cookies-li-list">Refunds are NOT given for any purchases made - be they online or in retail store.</li>
        <li class="cookies-li-list">We DO NOT encourage exchanges of our products.</li>
        <li class="cookies-li-list">We DO NOT engage in reselling used products and discourage the same, because we cannot ensure the best quality
            products for our customers.</li>
    </ul>


            <h4 class="cookies-heading-four">For International Orders:</h4>

            <ul class="cookies-unorder-list">
                <li class="cookies-li-list">We DO NOT support Exchanges or Returns.</li>
                <li class="cookies-li-list">If you cancel the order before we process it and dispatch for shipping, a refund can be processed. Orders generally take
                    1-2 days to process before dispatch.</li>
                <li class="cookies-li-list">Orders already in shipping cannot be returned, canceled or refunded.</li>
                <li class="cookies-li-list">If you face any issues, please contact our Support Team immediately.</li>
            </ul>


    <h2 class="cookies-heading-two">Your Consent</h2>
    <p class="cookies-content">By using our website, registering an account, or making a purchase, you hereby consent to our Return & Refund Policy and
        agree to its terms.</p>



        <h2 class="cookies-heading-two">Changes To Our Return & Refund Policy</h2>
        <p class="cookies-content">Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies.
            Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you
            will be bound by the updated Return & Refund Policy. If you do not want to agree to this or any updated Return & Refund Policy,
            you can delete your account.</p>


            <h2 class="cookies-heading-two">Contact Us</h2>
            <p class="cookies-content">If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we
                will discuss any of the issues you are going through with our product.</p>

                <ul class="cookies-unorder-list">
                    <li class="cookies-li-list">Via Email: help@starmapping.in</li>
                </ul>
</section> `;

    return () => {};
  }, []);

  return (
      
    <>
  <Header/>
    <div className="container" id="return"></div>
  <Footer/>


  </>
  
  
  )
}

export default Return;
